#[allow(dead_code)]
#[derive(Clone, Copy, Debug, PartialEq)]
#[repr(u8)]
pub enum CacheLevel {
    Unknown = 0,
    TLB = 1,
    L0TLB = 2,
    L1TLB = 3,
    L2TLB = 4,
    L0 = 100,
    L1 = 101,
    L2 = 102,
    L3 = 103,
    L4 = 104,
}

#[allow(dead_code)] // TODO: Remove when in use
#[derive(Clone, Copy, Debug, PartialEq)]
#[repr(u8)]
pub enum CacheType {
    Unknown = 0,
    Trace = 1,
    Code = 2,
    Data = 3,
    CodeAndData = 4,
}

#[allow(dead_code)] // TODO: Remove when in use
#[derive(Clone, Copy, Debug, PartialEq)]
#[repr(u16)]
pub enum CacheSize {
    Unknown = 0,
    Size4K = 1,
    Size8K = 2,
    Size16K = 3,
    Size24K = 4,
    Size32K = 5,
    Size48K = 6,
    Size96K = 7,
    Size128K = 8,
    Size192K = 9,
    Size256K = 10,
    Size384K = 11,
    Size512K = 12,
    Size1024K = 13,
    Size1536K = 14,
    Size2048K = 15,
    Size3072K = 16,
    Size4096K = 17,
    Size6144K = 18,
    Size8192K = 19,
    Size12288K = 20,
    Size16384K = 21,
    Size18432K = 22,
    Size24576K = 23,
    Size2M = 1000,
    Size4M = 1001,
    Size4K2M = 1002,
    Size4K4M = 1003,
    Size2M4M = 1004,
    Size4K2M4M = 1005,
    Size4K256M = 1006,
    Size1G = 1007,
    Size12KuOps = 2000,
    Size16KuOps = 2001,
    Size32KuOps = 2002,
    Size64KuOps = 2003,
}

#[allow(dead_code)] // TODO: Remove when in use
#[derive(Clone, Copy, Debug, PartialEq)]
#[repr(u8)]
pub enum CacheAssociativity {
    Unknown = 0,
    Assoc1Way = 1,
    Assoc2Way = 2,
    Assoc4Way = 3,
    Assoc6Way = 4,
    Assoc8Way = 5,
    Assoc12Way = 6,
    Assoc16Way = 7,
    Assoc24Way = 8,
    Fully = 99,
}

#[allow(dead_code)] // TODO: Remove when in use
#[derive(Clone, Copy, Debug, PartialEq)]
#[repr(u8)]
pub enum CacheLayoutType {
    Unknown = 0,
    Entries = 1,
    ByteLines = 2,
    MicroOps = 3,
}

#[allow(dead_code)] // TODO: Remove when in use
#[derive(Clone, Copy, Debug, PartialEq)]
#[repr(u8)]
pub enum CacheSectored {
    Unknown = 0,
    No = 1,
    Single = 2,
    Dual = 3,
}

#[allow(dead_code)] // TODO: Remove when in use
#[derive(Clone, Copy, Debug, PartialEq)]
pub struct CacheDescriptor {
    pub level: CacheLevel,
    pub type_of_cache: CacheType,
    pub size: CacheSize,
    pub associativity: CacheAssociativity,
    pub layout: CacheLayoutType,
    pub count: u32,
    pub ecc: bool,
    pub sectored: CacheSectored,
}

// Legacy configs CPUID(2)
pub const CACHE_CONFIGS: [CacheDescriptor; 0x100] = [
    CacheDescriptor { // NULL Descriptor - 0x00
        level: CacheLevel::Unknown,
        type_of_cache: CacheType::Unknown,
        size: CacheSize::Unknown,
        associativity: CacheAssociativity::Unknown,
        layout: CacheLayoutType::Unknown,
        count: 0,
        ecc: false,
        sectored: CacheSectored::No,
    },
    CacheDescriptor { // 0x01
        level: CacheLevel::TLB,
        type_of_cache: CacheType::Code,
        size: CacheSize::Size4K,
        associativity: CacheAssociativity::Assoc4Way,
        layout: CacheLayoutType::Entries,
        count: 32,
        ecc: false,
        sectored: CacheSectored::No,
    },
    CacheDescriptor { // 0x02
        level: CacheLevel::TLB,
        type_of_cache: CacheType::Code,
        size: CacheSize::Size4M,
        associativity: CacheAssociativity::Fully,
        layout: CacheLayoutType::Entries,
        count: 2,
        ecc: false,
        sectored: CacheSectored::No,
    },
    CacheDescriptor { // 0x03
        level: CacheLevel::TLB,
        type_of_cache: CacheType::Data,
        size: CacheSize::Size4K,
        associativity: CacheAssociativity::Assoc4Way,
        layout: CacheLayoutType::Entries,
        count: 64,
        ecc: false,
        sectored: CacheSectored::No,
    },
    CacheDescriptor { // 0x04
        level: CacheLevel::TLB,
        type_of_cache: CacheType::Data,
        size: CacheSize::Size4M,
        associativity: CacheAssociativity::Assoc4Way,
        layout: CacheLayoutType::Entries,
        count: 8,
        ecc: false,
        sectored: CacheSectored::No,
    },
    CacheDescriptor { // 0x05
        level: CacheLevel::TLB,
        type_of_cache: CacheType::Data,
        size: CacheSize::Size4M,
        associativity: CacheAssociativity::Assoc4Way,
        layout: CacheLayoutType::Entries,
        count: 32,
        ecc: false,
        sectored: CacheSectored::No,
    },
    CacheDescriptor { // 0x06
        level: CacheLevel::L1,
        type_of_cache: CacheType::Code,
        size: CacheSize::Size8K,
        associativity: CacheAssociativity::Assoc4Way,
        layout: CacheLayoutType::ByteLines,
        count: 32,
        ecc: false,
        sectored: CacheSectored::No,
    },
    CacheDescriptor { // 0x07 (UNKNOWN)
        level: CacheLevel::Unknown,
        type_of_cache: CacheType::Unknown,
        size: CacheSize::Unknown,
        associativity: CacheAssociativity::Unknown,
        layout: CacheLayoutType::Unknown,
        count: 0,
        ecc: false,
        sectored: CacheSectored::No,
    },
    CacheDescriptor { // 0x08
        level: CacheLevel::L1,
        type_of_cache: CacheType::Code,
        size: CacheSize::Size16K,
        associativity: CacheAssociativity::Assoc4Way,
        layout: CacheLayoutType::ByteLines,
        count: 32,
        ecc: false,
        sectored: CacheSectored::No,
    },
    CacheDescriptor { // 0x09
        level: CacheLevel::L1,
        type_of_cache: CacheType::Code,
        size: CacheSize::Size32K,
        associativity: CacheAssociativity::Assoc4Way,
        layout: CacheLayoutType::ByteLines,
        count: 64,
        ecc: false,
        sectored: CacheSectored::No,
    },
    CacheDescriptor { // 0x0A
        level: CacheLevel::L1,
        type_of_cache: CacheType::Data,
        size: CacheSize::Size8K,
        associativity: CacheAssociativity::Assoc2Way,
        layout: CacheLayoutType::ByteLines,
        count: 32,
        ecc: false,
        sectored: CacheSectored::No,
    },
    CacheDescriptor { // 0x0B
        level: CacheLevel::TLB,
        type_of_cache: CacheType::Code,
        size: CacheSize::Size4M,
        associativity: CacheAssociativity::Assoc4Way,
        layout: CacheLayoutType::Entries,
        count: 4,
        ecc: false,
        sectored: CacheSectored::No,
    },
    CacheDescriptor { // 0x0C
        level: CacheLevel::L1,
        type_of_cache: CacheType::Data,
        size: CacheSize::Size16K,
        associativity: CacheAssociativity::Assoc4Way,
        layout: CacheLayoutType::ByteLines,
        count: 32,
        ecc: false,
        sectored: CacheSectored::No,
    },
    CacheDescriptor { // 0x0D
        level: CacheLevel::L1,
        type_of_cache: CacheType::Data,
        size: CacheSize::Size16K,
        associativity: CacheAssociativity::Assoc4Way,
        layout: CacheLayoutType::ByteLines,
        count: 64,
        ecc: true,
        sectored: CacheSectored::No,
    },
    CacheDescriptor { // 0x0E
        level: CacheLevel::L1,
        type_of_cache: CacheType::Data,
        size: CacheSize::Size24K,
        associativity: CacheAssociativity::Assoc6Way,
        layout: CacheLayoutType::ByteLines,
        count: 64,
        ecc: false,
        sectored: CacheSectored::No,
    },
    CacheDescriptor { // 0x0F (UNKNOWN)
        level: CacheLevel::Unknown,
        type_of_cache: CacheType::Unknown,
        size: CacheSize::Unknown,
        associativity: CacheAssociativity::Unknown,
        layout: CacheLayoutType::Unknown,
        count: 0,
        ecc: false,
        sectored: CacheSectored::No,
    },
    CacheDescriptor { // 0x10
        level: CacheLevel::L1,
        type_of_cache: CacheType::Data,
        size: CacheSize::Size16K,
        associativity: CacheAssociativity::Assoc4Way,
        layout: CacheLayoutType::ByteLines,
        count: 32,
        ecc: false,
        sectored: CacheSectored::No,
    },
    CacheDescriptor { // 0x11 (UNKNOWN)
        level: CacheLevel::Unknown,
        type_of_cache: CacheType::Unknown,
        size: CacheSize::Unknown,
        associativity: CacheAssociativity::Unknown,
        layout: CacheLayoutType::Unknown,
        count: 0,
        ecc: false,
        sectored: CacheSectored::No,
    },
    CacheDescriptor { // 0x12 (UNKNOWN)
        level: CacheLevel::Unknown,
        type_of_cache: CacheType::Unknown,
        size: CacheSize::Unknown,
        associativity: CacheAssociativity::Unknown,
        layout: CacheLayoutType::Unknown,
        count: 0,
        ecc: false,
        sectored: CacheSectored::No,
    },
    CacheDescriptor { // 0x13 (UNKNOWN)
        level: CacheLevel::Unknown,
        type_of_cache: CacheType::Unknown,
        size: CacheSize::Unknown,
        associativity: CacheAssociativity::Unknown,
        layout: CacheLayoutType::Unknown,
        count: 0,
        ecc: false,
        sectored: CacheSectored::No,
    },
    CacheDescriptor { // 0x14 (UNKNOWN)
        level: CacheLevel::Unknown,
        type_of_cache: CacheType::Unknown,
        size: CacheSize::Unknown,
        associativity: CacheAssociativity::Unknown,
        layout: CacheLayoutType::Unknown,
        count: 0,
        ecc: false,
        sectored: CacheSectored::No,
    },
    CacheDescriptor { // 0x15
        level: CacheLevel::L1,
        type_of_cache: CacheType::Code,
        size: CacheSize::Size16K,
        associativity: CacheAssociativity::Assoc4Way,
        layout: CacheLayoutType::ByteLines,
        count: 32,
        ecc: false,
        sectored: CacheSectored::No,
    },
    CacheDescriptor { // 0x16 (UNKNOWN)
        level: CacheLevel::Unknown,
        type_of_cache: CacheType::Unknown,
        size: CacheSize::Unknown,
        associativity: CacheAssociativity::Unknown,
        layout: CacheLayoutType::Unknown,
        count: 0,
        ecc: false,
        sectored: CacheSectored::No,
    },
    CacheDescriptor { // 0x17 (UNKNOWN)
        level: CacheLevel::Unknown,
        type_of_cache: CacheType::Unknown,
        size: CacheSize::Unknown,
        associativity: CacheAssociativity::Unknown,
        layout: CacheLayoutType::Unknown,
        count: 0,
        ecc: false,
        sectored: CacheSectored::No,
    },
    CacheDescriptor { // 0x18 (UNKNOWN)
        level: CacheLevel::Unknown,
        type_of_cache: CacheType::Unknown,
        size: CacheSize::Unknown,
        associativity: CacheAssociativity::Unknown,
        layout: CacheLayoutType::Unknown,
        count: 0,
        ecc: false,
        sectored: CacheSectored::No,
    },
    CacheDescriptor { // 0x19 (UNKNOWN)
        level: CacheLevel::Unknown,
        type_of_cache: CacheType::Unknown,
        size: CacheSize::Unknown,
        associativity: CacheAssociativity::Unknown,
        layout: CacheLayoutType::Unknown,
        count: 0,
        ecc: false,
        sectored: CacheSectored::No,
    },
    CacheDescriptor { // 0x1A
        level: CacheLevel::L2,
        type_of_cache: CacheType::CodeAndData,
        size: CacheSize::Size96K,
        associativity: CacheAssociativity::Assoc6Way,
        layout: CacheLayoutType::ByteLines,
        count: 64,
        ecc: false,
        sectored: CacheSectored::No,
    },
    CacheDescriptor { // 0x1B (UNKNOWN)
        level: CacheLevel::Unknown,
        type_of_cache: CacheType::Unknown,
        size: CacheSize::Unknown,
        associativity: CacheAssociativity::Unknown,
        layout: CacheLayoutType::Unknown,
        count: 0,
        ecc: false,
        sectored: CacheSectored::No,
    },
    CacheDescriptor { // 0x1C (UNKNOWN)
        level: CacheLevel::Unknown,
        type_of_cache: CacheType::Unknown,
        size: CacheSize::Unknown,
        associativity: CacheAssociativity::Unknown,
        layout: CacheLayoutType::Unknown,
        count: 0,
        ecc: false,
        sectored: CacheSectored::No,
    },
    CacheDescriptor { // 0x1D
        level: CacheLevel::L2,
        type_of_cache: CacheType::CodeAndData,
        size: CacheSize::Size128K,
        associativity: CacheAssociativity::Assoc2Way,
        layout: CacheLayoutType::ByteLines,
        count: 64,
        ecc: false,
        sectored: CacheSectored::No,
    },
    CacheDescriptor { // 0x1E (UNKNOWN)
        level: CacheLevel::Unknown,
        type_of_cache: CacheType::Unknown,
        size: CacheSize::Unknown,
        associativity: CacheAssociativity::Unknown,
        layout: CacheLayoutType::Unknown,
        count: 0,
        ecc: false,
        sectored: CacheSectored::No,
    },
    CacheDescriptor { // 0x1F (UNKNOWN)
        level: CacheLevel::Unknown,
        type_of_cache: CacheType::Unknown,
        size: CacheSize::Unknown,
        associativity: CacheAssociativity::Unknown,
        layout: CacheLayoutType::Unknown,
        count: 0,
        ecc: false,
        sectored: CacheSectored::No,
    },
    CacheDescriptor { // 0x20 (UNKNOWN)
        level: CacheLevel::Unknown,
        type_of_cache: CacheType::Unknown,
        size: CacheSize::Unknown,
        associativity: CacheAssociativity::Unknown,
        layout: CacheLayoutType::Unknown,
        count: 0,
        ecc: false,
        sectored: CacheSectored::No,
    },
    CacheDescriptor { // 0x21
        level: CacheLevel::L2,
        type_of_cache: CacheType::CodeAndData,
        size: CacheSize::Size256K,
        associativity: CacheAssociativity::Assoc8Way,
        layout: CacheLayoutType::ByteLines,
        count: 64,
        ecc: false,
        sectored: CacheSectored::No,
    },
    CacheDescriptor { // 0x22
        level: CacheLevel::L3,
        type_of_cache: CacheType::CodeAndData,
        size: CacheSize::Size512K,
        associativity: CacheAssociativity::Assoc4Way,
        layout: CacheLayoutType::ByteLines,
        count: 64,
        ecc: false,
        sectored: CacheSectored::Dual,
    },
    CacheDescriptor { // 0x23
        level: CacheLevel::L3,
        type_of_cache: CacheType::CodeAndData,
        size: CacheSize::Size1024K,
        associativity: CacheAssociativity::Assoc8Way,
        layout: CacheLayoutType::ByteLines,
        count: 64,
        ecc: false,
        sectored: CacheSectored::Dual,
    },
    CacheDescriptor { // 0x24
        level: CacheLevel::L2,
        type_of_cache: CacheType::CodeAndData,
        size: CacheSize::Size1024K,
        associativity: CacheAssociativity::Assoc16Way,
        layout: CacheLayoutType::ByteLines,
        count: 64,
        ecc: false,
        sectored: CacheSectored::No,
    },
    CacheDescriptor { // 0x25
        level: CacheLevel::L3,
        type_of_cache: CacheType::CodeAndData,
        size: CacheSize::Size2048K,
        associativity: CacheAssociativity::Assoc8Way,
        layout: CacheLayoutType::ByteLines,
        count: 64,
        ecc: false,
        sectored: CacheSectored::Dual,
    },
    CacheDescriptor { // 0x26 (UNKNOWN)
        level: CacheLevel::Unknown,
        type_of_cache: CacheType::Unknown,
        size: CacheSize::Unknown,
        associativity: CacheAssociativity::Unknown,
        layout: CacheLayoutType::Unknown,
        count: 0,
        ecc: false,
        sectored: CacheSectored::No,
    },
    CacheDescriptor { // 0x27 (UNKNOWN)
        level: CacheLevel::Unknown,
        type_of_cache: CacheType::Unknown,
        size: CacheSize::Unknown,
        associativity: CacheAssociativity::Unknown,
        layout: CacheLayoutType::Unknown,
        count: 0,
        ecc: false,
        sectored: CacheSectored::No,
    },
    CacheDescriptor { // 0x28 (UNKNOWN)
        level: CacheLevel::Unknown,
        type_of_cache: CacheType::Unknown,
        size: CacheSize::Unknown,
        associativity: CacheAssociativity::Unknown,
        layout: CacheLayoutType::Unknown,
        count: 0,
        ecc: false,
        sectored: CacheSectored::No,
    },
    CacheDescriptor { // 0x29
        level: CacheLevel::L3,
        type_of_cache: CacheType::CodeAndData,
        size: CacheSize::Size4096K,
        associativity: CacheAssociativity::Assoc8Way,
        layout: CacheLayoutType::ByteLines,
        count: 64,
        ecc: false,
        sectored: CacheSectored::Dual,
    },
    CacheDescriptor { // 0x2A (UNKNOWN)
        level: CacheLevel::Unknown,
        type_of_cache: CacheType::Unknown,
        size: CacheSize::Unknown,
        associativity: CacheAssociativity::Unknown,
        layout: CacheLayoutType::Unknown,
        count: 0,
        ecc: false,
        sectored: CacheSectored::No,
    },
    CacheDescriptor { // 0x2B (UNKNOWN)
        level: CacheLevel::Unknown,
        type_of_cache: CacheType::Unknown,
        size: CacheSize::Unknown,
        associativity: CacheAssociativity::Unknown,
        layout: CacheLayoutType::Unknown,
        count: 0,
        ecc: false,
        sectored: CacheSectored::No,
    },
    CacheDescriptor { // 0x2C
        level: CacheLevel::L1,
        type_of_cache: CacheType::Data,
        size: CacheSize::Size32K,
        associativity: CacheAssociativity::Assoc8Way,
        layout: CacheLayoutType::ByteLines,
        count: 64,
        ecc: false,
        sectored: CacheSectored::No,
    },
    CacheDescriptor { // 0x2D (UNKNOWN)
        level: CacheLevel::Unknown,
        type_of_cache: CacheType::Unknown,
        size: CacheSize::Unknown,
        associativity: CacheAssociativity::Unknown,
        layout: CacheLayoutType::Unknown,
        count: 0,
        ecc: false,
        sectored: CacheSectored::No,
    },
    CacheDescriptor { // 0x2E (UNKNOWN)
        level: CacheLevel::Unknown,
        type_of_cache: CacheType::Unknown,
        size: CacheSize::Unknown,
        associativity: CacheAssociativity::Unknown,
        layout: CacheLayoutType::Unknown,
        count: 0,
        ecc: false,
        sectored: CacheSectored::No,
    },
    CacheDescriptor { // 0x2F (UNKNOWN)
        level: CacheLevel::Unknown,
        type_of_cache: CacheType::Unknown,
        size: CacheSize::Unknown,
        associativity: CacheAssociativity::Unknown,
        layout: CacheLayoutType::Unknown,
        count: 0,
        ecc: false,
        sectored: CacheSectored::No,
    },
    CacheDescriptor { // 0x30
        level: CacheLevel::L1,
        type_of_cache: CacheType::Code,
        size: CacheSize::Size32K,
        associativity: CacheAssociativity::Assoc8Way,
        layout: CacheLayoutType::ByteLines,
        count: 64,
        ecc: false,
        sectored: CacheSectored::No,
    },
    CacheDescriptor { // 0x31 (UNKNOWN)
        level: CacheLevel::Unknown,
        type_of_cache: CacheType::Unknown,
        size: CacheSize::Unknown,
        associativity: CacheAssociativity::Unknown,
        layout: CacheLayoutType::Unknown,
        count: 0,
        ecc: false,
        sectored: CacheSectored::No,
    },
    CacheDescriptor { // 0x32 (UNKNOWN)
        level: CacheLevel::Unknown,
        type_of_cache: CacheType::Unknown,
        size: CacheSize::Unknown,
        associativity: CacheAssociativity::Unknown,
        layout: CacheLayoutType::Unknown,
        count: 0,
        ecc: false,
        sectored: CacheSectored::No,
    },
    CacheDescriptor { // 0x33 (UNKNOWN)
        level: CacheLevel::Unknown,
        type_of_cache: CacheType::Unknown,
        size: CacheSize::Unknown,
        associativity: CacheAssociativity::Unknown,
        layout: CacheLayoutType::Unknown,
        count: 0,
        ecc: false,
        sectored: CacheSectored::No,
    },
    CacheDescriptor { // 0x34 (UNKNOWN)
        level: CacheLevel::Unknown,
        type_of_cache: CacheType::Unknown,
        size: CacheSize::Unknown,
        associativity: CacheAssociativity::Unknown,
        layout: CacheLayoutType::Unknown,
        count: 0,
        ecc: false,
        sectored: CacheSectored::No,
    },
    CacheDescriptor { // 0x35 (UNKNOWN)
        level: CacheLevel::Unknown,
        type_of_cache: CacheType::Unknown,
        size: CacheSize::Unknown,
        associativity: CacheAssociativity::Unknown,
        layout: CacheLayoutType::Unknown,
        count: 0,
        ecc: false,
        sectored: CacheSectored::No,
    },
    CacheDescriptor { // 0x36 (UNKNOWN)
        level: CacheLevel::Unknown,
        type_of_cache: CacheType::Unknown,
        size: CacheSize::Unknown,
        associativity: CacheAssociativity::Unknown,
        layout: CacheLayoutType::Unknown,
        count: 0,
        ecc: false,
        sectored: CacheSectored::No,
    },
    CacheDescriptor { // 0x37 (UNKNOWN)
        level: CacheLevel::Unknown,
        type_of_cache: CacheType::Unknown,
        size: CacheSize::Unknown,
        associativity: CacheAssociativity::Unknown,
        layout: CacheLayoutType::Unknown,
        count: 0,
        ecc: false,
        sectored: CacheSectored::No,
    },
    CacheDescriptor { // 0x38 (UNKNOWN)
        level: CacheLevel::Unknown,
        type_of_cache: CacheType::Unknown,
        size: CacheSize::Unknown,
        associativity: CacheAssociativity::Unknown,
        layout: CacheLayoutType::Unknown,
        count: 0,
        ecc: false,
        sectored: CacheSectored::No,
    },
    CacheDescriptor { // 0x39
        level: CacheLevel::L2,
        type_of_cache: CacheType::CodeAndData,
        size: CacheSize::Size128K,
        associativity: CacheAssociativity::Assoc4Way,
        layout: CacheLayoutType::ByteLines,
        count: 64,
        ecc: false,
        sectored: CacheSectored::Single,
    },
    CacheDescriptor { // 0x3A
        level: CacheLevel::L2,
        type_of_cache: CacheType::CodeAndData,
        size: CacheSize::Size192K,
        associativity: CacheAssociativity::Assoc6Way,
        layout: CacheLayoutType::ByteLines,
        count: 64,
        ecc: false,
        sectored: CacheSectored::Single,
    },
    CacheDescriptor { // 0x3B
        level: CacheLevel::L2,
        type_of_cache: CacheType::CodeAndData,
        size: CacheSize::Size128K,
        associativity: CacheAssociativity::Assoc2Way,
        layout: CacheLayoutType::ByteLines,
        count: 64,
        ecc: false,
        sectored: CacheSectored::Single,
    },
    CacheDescriptor { // 0x3C
        level: CacheLevel::L2,
        type_of_cache: CacheType::CodeAndData,
        size: CacheSize::Size256K,
        associativity: CacheAssociativity::Assoc4Way,
        layout: CacheLayoutType::ByteLines,
        count: 64,
        ecc: false,
        sectored: CacheSectored::Single,
    },
    CacheDescriptor { // 0x3D
        level: CacheLevel::L2,
        type_of_cache: CacheType::CodeAndData,
        size: CacheSize::Size384K,
        associativity: CacheAssociativity::Assoc6Way,
        layout: CacheLayoutType::ByteLines,
        count: 64,
        ecc: false,
        sectored: CacheSectored::Single,
    },
    CacheDescriptor { // 0x3E
        level: CacheLevel::L2,
        type_of_cache: CacheType::CodeAndData,
        size: CacheSize::Size512K,
        associativity: CacheAssociativity::Assoc4Way,
        layout: CacheLayoutType::ByteLines,
        count: 64,
        ecc: false,
        sectored: CacheSectored::Single,
    },
    CacheDescriptor { // 0x3F (UNKNOWN)
        level: CacheLevel::Unknown,
        type_of_cache: CacheType::Unknown,
        size: CacheSize::Unknown,
        associativity: CacheAssociativity::Unknown,
        layout: CacheLayoutType::Unknown,
        count: 0,
        ecc: false,
        sectored: CacheSectored::No,
    },
    CacheDescriptor { // 0x40
        level: CacheLevel::L2,
        type_of_cache: CacheType::Unknown,
        size: CacheSize::Unknown,
        associativity: CacheAssociativity::Unknown,
        layout: CacheLayoutType::Unknown,
        count: 0,
        ecc: false,
        sectored: CacheSectored::No,
    },
    CacheDescriptor { // 0x41
        level: CacheLevel::L2,
        type_of_cache: CacheType::CodeAndData,
        size: CacheSize::Size128K,
        associativity: CacheAssociativity::Assoc4Way,
        layout: CacheLayoutType::ByteLines,
        count: 32,
        ecc: false,
        sectored: CacheSectored::No,
    },
    CacheDescriptor { // 0x42
        level: CacheLevel::L2,
        type_of_cache: CacheType::CodeAndData,
        size: CacheSize::Size256K,
        associativity: CacheAssociativity::Assoc4Way,
        layout: CacheLayoutType::ByteLines,
        count: 32,
        ecc: false,
        sectored: CacheSectored::No,
    },
    CacheDescriptor { // 0x43
        level: CacheLevel::L2,
        type_of_cache: CacheType::CodeAndData,
        size: CacheSize::Size512K,
        associativity: CacheAssociativity::Assoc4Way,
        layout: CacheLayoutType::ByteLines,
        count: 32,
        ecc: false,
        sectored: CacheSectored::No,
    },
    CacheDescriptor { // 0x44
        level: CacheLevel::L2,
        type_of_cache: CacheType::CodeAndData,
        size: CacheSize::Size1024K,
        associativity: CacheAssociativity::Assoc4Way,
        layout: CacheLayoutType::ByteLines,
        count: 32,
        ecc: false,
        sectored: CacheSectored::No,
    },
    CacheDescriptor { // 0x45
        level: CacheLevel::L2,
        type_of_cache: CacheType::CodeAndData,
        size: CacheSize::Size2048K,
        associativity: CacheAssociativity::Assoc4Way,
        layout: CacheLayoutType::ByteLines,
        count: 32,
        ecc: false,
        sectored: CacheSectored::No,
    },
    CacheDescriptor { // 0x46
        level: CacheLevel::L3,
        type_of_cache: CacheType::CodeAndData,
        size: CacheSize::Size4096K,
        associativity: CacheAssociativity::Assoc4Way,
        layout: CacheLayoutType::ByteLines,
        count: 64,
        ecc: false,
        sectored: CacheSectored::No,
    },
    CacheDescriptor { // 0x47
        level: CacheLevel::L3,
        type_of_cache: CacheType::CodeAndData,
        size: CacheSize::Size8192K,
        associativity: CacheAssociativity::Assoc8Way,
        layout: CacheLayoutType::ByteLines,
        count: 64,
        ecc: false,
        sectored: CacheSectored::No,
    },
    CacheDescriptor { // 0x48
        level: CacheLevel::L2,
        type_of_cache: CacheType::CodeAndData,
        size: CacheSize::Size3072K,
        associativity: CacheAssociativity::Assoc12Way,
        layout: CacheLayoutType::ByteLines,
        count: 64,
        ecc: false,
        sectored: CacheSectored::No,
    },
    CacheDescriptor { // 0x49 - !! is L3 cache on P4 !!
        level: CacheLevel::L2,
        type_of_cache: CacheType::CodeAndData,
        size: CacheSize::Size4096K,
        associativity: CacheAssociativity::Assoc16Way,
        layout: CacheLayoutType::ByteLines,
        count: 64,
        ecc: false,
        sectored: CacheSectored::No,
    },
    CacheDescriptor { // 0x4A
        level: CacheLevel::L3,
        type_of_cache: CacheType::CodeAndData,
        size: CacheSize::Size6144K,
        associativity: CacheAssociativity::Assoc12Way,
        layout: CacheLayoutType::ByteLines,
        count: 64,
        ecc: false,
        sectored: CacheSectored::No,
    },
    CacheDescriptor { // 0x4B
        level: CacheLevel::L3,
        type_of_cache: CacheType::CodeAndData,
        size: CacheSize::Size8192K,
        associativity: CacheAssociativity::Assoc16Way,
        layout: CacheLayoutType::ByteLines,
        count: 64,
        ecc: false,
        sectored: CacheSectored::No,
    },
    CacheDescriptor { // 0x4C
        level: CacheLevel::L3,
        type_of_cache: CacheType::CodeAndData,
        size: CacheSize::Size12288K,
        associativity: CacheAssociativity::Assoc12Way,
        layout: CacheLayoutType::ByteLines,
        count: 64,
        ecc: false,
        sectored: CacheSectored::No,
    },
    CacheDescriptor { // 0x4D
        level: CacheLevel::L3,
        type_of_cache: CacheType::CodeAndData,
        size: CacheSize::Size16384K,
        associativity: CacheAssociativity::Assoc16Way,
        layout: CacheLayoutType::ByteLines,
        count: 64,
        ecc: false,
        sectored: CacheSectored::No,
    },
    CacheDescriptor { // 0x4E
        level: CacheLevel::L2,
        type_of_cache: CacheType::CodeAndData,
        size: CacheSize::Size6144K,
        associativity: CacheAssociativity::Assoc24Way,
        layout: CacheLayoutType::ByteLines,
        count: 64,
        ecc: false,
        sectored: CacheSectored::No,
    },
    CacheDescriptor { // 0x4F
        level: CacheLevel::TLB,
        type_of_cache: CacheType::Code,
        size: CacheSize::Size128K,
        associativity: CacheAssociativity::Assoc4Way,
        layout: CacheLayoutType::Entries,
        count: 32,
        ecc: false,
        sectored: CacheSectored::No,
    },
    CacheDescriptor { // 0x50
        level: CacheLevel::TLB,
        type_of_cache: CacheType::Code,
        size: CacheSize::Size4K2M4M,
        associativity: CacheAssociativity::Fully,
        layout: CacheLayoutType::Entries,
        count: 64,
        ecc: false,
        sectored: CacheSectored::No,
    },
    CacheDescriptor { // 0x51
        level: CacheLevel::TLB,
        type_of_cache: CacheType::Code,
        size: CacheSize::Size4K2M4M,
        associativity: CacheAssociativity::Fully,
        layout: CacheLayoutType::Entries,
        count: 128,
        ecc: false,
        sectored: CacheSectored::No,
    },
    CacheDescriptor { // 0x52
        level: CacheLevel::TLB,
        type_of_cache: CacheType::Code,
        size: CacheSize::Size4K2M4M,
        associativity: CacheAssociativity::Fully,
        layout: CacheLayoutType::Entries,
        count: 256,
        ecc: false,
        sectored: CacheSectored::No,
    },
    CacheDescriptor { // 0x53 (UNKNOWN)
        level: CacheLevel::Unknown,
        type_of_cache: CacheType::Unknown,
        size: CacheSize::Unknown,
        associativity: CacheAssociativity::Unknown,
        layout: CacheLayoutType::Unknown,
        count: 0,
        ecc: false,
        sectored: CacheSectored::No,
    },
    CacheDescriptor { // 0x54 (UNKNOWN)
        level: CacheLevel::Unknown,
        type_of_cache: CacheType::Unknown,
        size: CacheSize::Unknown,
        associativity: CacheAssociativity::Unknown,
        layout: CacheLayoutType::Unknown,
        count: 0,
        ecc: false,
        sectored: CacheSectored::No,
    },
    CacheDescriptor { // 0x55
        level: CacheLevel::TLB,
        type_of_cache: CacheType::Code,
        size: CacheSize::Size2M4M,
        associativity: CacheAssociativity::Fully,
        layout: CacheLayoutType::Entries,
        count: 7,
        ecc: false,
        sectored: CacheSectored::No,
    },
    CacheDescriptor { // 0x56
        level: CacheLevel::L0TLB,
        type_of_cache: CacheType::Data,
        size: CacheSize::Size4M,
        associativity: CacheAssociativity::Assoc4Way,
        layout: CacheLayoutType::Entries,
        count: 16,
        ecc: false,
        sectored: CacheSectored::No,
    },
    CacheDescriptor { // 0x57
        level: CacheLevel::L0TLB,
        type_of_cache: CacheType::Data,
        size: CacheSize::Size4K,
        associativity: CacheAssociativity::Assoc4Way,
        layout: CacheLayoutType::Entries,
        count: 16,
        ecc: false,
        sectored: CacheSectored::No,
    },
    CacheDescriptor { // 0x58 (UNKNOWN)
        level: CacheLevel::Unknown,
        type_of_cache: CacheType::Unknown,
        size: CacheSize::Unknown,
        associativity: CacheAssociativity::Unknown,
        layout: CacheLayoutType::Unknown,
        count: 0,
        ecc: false,
        sectored: CacheSectored::No,
    },
    CacheDescriptor { // 0x59
        level: CacheLevel::L0TLB,
        type_of_cache: CacheType::Data,
        size: CacheSize::Size4M,
        associativity: CacheAssociativity::Fully,
        layout: CacheLayoutType::Entries,
        count: 16,
        ecc: false,
        sectored: CacheSectored::No,
    },
    CacheDescriptor { // 0x5A
        level: CacheLevel::L0TLB,
        type_of_cache: CacheType::Data,
        size: CacheSize::Size2M4M,
        associativity: CacheAssociativity::Assoc4Way,
        layout: CacheLayoutType::Entries,
        count: 32,
        ecc: false,
        sectored: CacheSectored::No,
    },
    CacheDescriptor { // 0x5B
        level: CacheLevel::TLB,
        type_of_cache: CacheType::Data,
        size: CacheSize::Size4K4M,
        associativity: CacheAssociativity::Fully,
        layout: CacheLayoutType::Entries,
        count: 64,
        ecc: false,
        sectored: CacheSectored::No,
    },
    CacheDescriptor { // 0x5C
        level: CacheLevel::TLB,
        type_of_cache: CacheType::Data,
        size: CacheSize::Size4K4M,
        associativity: CacheAssociativity::Fully,
        layout: CacheLayoutType::Entries,
        count: 128,
        ecc: false,
        sectored: CacheSectored::No,
    },
    CacheDescriptor { // 0x5D
        level: CacheLevel::TLB,
        type_of_cache: CacheType::Data,
        size: CacheSize::Size4K4M,
        associativity: CacheAssociativity::Fully,
        layout: CacheLayoutType::Entries,
        count: 256,
        ecc: false,
        sectored: CacheSectored::No,
    },
    CacheDescriptor { // 0x5E (UNKNOWN)
        level: CacheLevel::Unknown,
        type_of_cache: CacheType::Unknown,
        size: CacheSize::Unknown,
        associativity: CacheAssociativity::Unknown,
        layout: CacheLayoutType::Unknown,
        count: 0,
        ecc: false,
        sectored: CacheSectored::No,
    },
    CacheDescriptor { // 0x5F (UNKNOWN)
        level: CacheLevel::Unknown,
        type_of_cache: CacheType::Unknown,
        size: CacheSize::Unknown,
        associativity: CacheAssociativity::Unknown,
        layout: CacheLayoutType::Unknown,
        count: 0,
        ecc: false,
        sectored: CacheSectored::No,
    },
    CacheDescriptor { // 0x60
        level: CacheLevel::L1,
        type_of_cache: CacheType::Data,
        size: CacheSize::Size16K,
        associativity: CacheAssociativity::Assoc8Way,
        layout: CacheLayoutType::ByteLines,
        count: 64,
        ecc: false,
        sectored: CacheSectored::Single,
    },
    CacheDescriptor { // 0x61
        level: CacheLevel::TLB,
        type_of_cache: CacheType::Code,
        size: CacheSize::Size4K,
        associativity: CacheAssociativity::Fully,
        layout: CacheLayoutType::Entries,
        count: 48,
        ecc: false,
        sectored: CacheSectored::No,
    },
    CacheDescriptor { // 0x62 (UNKNOWN)
        level: CacheLevel::Unknown,
        type_of_cache: CacheType::Unknown,
        size: CacheSize::Unknown,
        associativity: CacheAssociativity::Unknown,
        layout: CacheLayoutType::Unknown,
        count: 0,
        ecc: false,
        sectored: CacheSectored::No,
    },
    CacheDescriptor { // 0x63
        level: CacheLevel::TLB,
        type_of_cache: CacheType::Code,
        size: CacheSize::Size2M4M,
        associativity: CacheAssociativity::Assoc4Way,
        layout: CacheLayoutType::Entries,
        count: 32,
        ecc: false,
        sectored: CacheSectored::No,
    },
    CacheDescriptor { // 0x64
        level: CacheLevel::TLB,
        type_of_cache: CacheType::Data,
        size: CacheSize::Size4K,
        associativity: CacheAssociativity::Assoc4Way,
        layout: CacheLayoutType::Entries,
        count: 512,
        ecc: false,
        sectored: CacheSectored::No,
    },
    CacheDescriptor { // 0x65 (UNKNOWN)
        level: CacheLevel::Unknown,
        type_of_cache: CacheType::Unknown,
        size: CacheSize::Unknown,
        associativity: CacheAssociativity::Unknown,
        layout: CacheLayoutType::Unknown,
        count: 0,
        ecc: false,
        sectored: CacheSectored::No,
    },
    CacheDescriptor { // 0x66
        level: CacheLevel::L1,
        type_of_cache: CacheType::Data,
        size: CacheSize::Size8K,
        associativity: CacheAssociativity::Assoc4Way,
        layout: CacheLayoutType::ByteLines,
        count: 64,
        ecc: false,
        sectored: CacheSectored::Single,
    },
    CacheDescriptor { // 0x67
        level: CacheLevel::L1,
        type_of_cache: CacheType::Data,
        size: CacheSize::Size16K,
        associativity: CacheAssociativity::Assoc4Way,
        layout: CacheLayoutType::ByteLines,
        count: 64,
        ecc: false,
        sectored: CacheSectored::Single,
    },
    CacheDescriptor { // 0x68
        level: CacheLevel::L1,
        type_of_cache: CacheType::Data,
        size: CacheSize::Size32K,
        associativity: CacheAssociativity::Assoc4Way,
        layout: CacheLayoutType::ByteLines,
        count: 64,
        ecc: false,
        sectored: CacheSectored::Single,
    },
    CacheDescriptor { // 0x69 (UNKNOWN)
        level: CacheLevel::Unknown,
        type_of_cache: CacheType::Unknown,
        size: CacheSize::Unknown,
        associativity: CacheAssociativity::Unknown,
        layout: CacheLayoutType::Unknown,
        count: 0,
        ecc: false,
        sectored: CacheSectored::No,
    },
    CacheDescriptor { // 0x6A
        level: CacheLevel::L0TLB,
        type_of_cache: CacheType::Data,
        size: CacheSize::Size4K,
        associativity: CacheAssociativity::Assoc8Way,
        layout: CacheLayoutType::Entries,
        count: 64,
        ecc: false,
        sectored: CacheSectored::No,
    },
    CacheDescriptor { // 0x6B
        level: CacheLevel::TLB,
        type_of_cache: CacheType::Data,
        size: CacheSize::Size4K,
        associativity: CacheAssociativity::Assoc8Way,
        layout: CacheLayoutType::Entries,
        count: 256,
        ecc: false,
        sectored: CacheSectored::No,
    },
    CacheDescriptor { // 0x6C
        level: CacheLevel::TLB,
        type_of_cache: CacheType::Data,
        size: CacheSize::Size2M4M,
        associativity: CacheAssociativity::Assoc8Way,
        layout: CacheLayoutType::Entries,
        count: 128,
        ecc: false,
        sectored: CacheSectored::No,
    },
    CacheDescriptor { // 0x6D
        level: CacheLevel::TLB,
        type_of_cache: CacheType::Data,
        size: CacheSize::Size1G,
        associativity: CacheAssociativity::Fully,
        layout: CacheLayoutType::Entries,
        count: 16,
        ecc: false,
        sectored: CacheSectored::No,
    },
    CacheDescriptor { // 0x6E (UNKNOWN)
        level: CacheLevel::Unknown,
        type_of_cache: CacheType::Unknown,
        size: CacheSize::Unknown,
        associativity: CacheAssociativity::Unknown,
        layout: CacheLayoutType::Unknown,
        count: 0,
        ecc: false,
        sectored: CacheSectored::No,
    },
    CacheDescriptor { // 0x6F (UNKNOWN)
        level: CacheLevel::Unknown,
        type_of_cache: CacheType::Unknown,
        size: CacheSize::Unknown,
        associativity: CacheAssociativity::Unknown,
        layout: CacheLayoutType::Unknown,
        count: 0,
        ecc: false,
        sectored: CacheSectored::No,
    },
    CacheDescriptor { // 0x70
        level: CacheLevel::L1,
        type_of_cache: CacheType::Trace,
        size: CacheSize::Size12KuOps,
        associativity: CacheAssociativity::Assoc8Way,
        layout: CacheLayoutType::MicroOps,
        count: 0,
        ecc: false,
        sectored: CacheSectored::No,
    },
    CacheDescriptor { // 0x71
        level: CacheLevel::L1,
        type_of_cache: CacheType::Trace,
        size: CacheSize::Size16KuOps,
        associativity: CacheAssociativity::Assoc8Way,
        layout: CacheLayoutType::MicroOps,
        count: 0,
        ecc: false,
        sectored: CacheSectored::No,
    },
    CacheDescriptor { // 0x72
        level: CacheLevel::L1,
        type_of_cache: CacheType::Trace,
        size: CacheSize::Size32KuOps,
        associativity: CacheAssociativity::Assoc8Way,
        layout: CacheLayoutType::MicroOps,
        count: 0,
        ecc: false,
        sectored: CacheSectored::No,
    },
    CacheDescriptor { // 0x73
        level: CacheLevel::L1,
        type_of_cache: CacheType::Trace,
        size: CacheSize::Size64KuOps,
        associativity: CacheAssociativity::Assoc8Way,
        layout: CacheLayoutType::MicroOps,
        count: 0,
        ecc: false,
        sectored: CacheSectored::No,
    },
    CacheDescriptor { // 0x74 (UNKNOWN)
        level: CacheLevel::Unknown,
        type_of_cache: CacheType::Unknown,
        size: CacheSize::Unknown,
        associativity: CacheAssociativity::Unknown,
        layout: CacheLayoutType::Unknown,
        count: 0,
        ecc: false,
        sectored: CacheSectored::No,
    },
    CacheDescriptor { // 0x75 (UNKNOWN)
        level: CacheLevel::Unknown,
        type_of_cache: CacheType::Unknown,
        size: CacheSize::Unknown,
        associativity: CacheAssociativity::Unknown,
        layout: CacheLayoutType::Unknown,
        count: 0,
        ecc: false,
        sectored: CacheSectored::No,
    },
    CacheDescriptor { // 0x76
        level: CacheLevel::TLB,
        type_of_cache: CacheType::Code,
        size: CacheSize::Size2M4M,
        associativity: CacheAssociativity::Fully,
        layout: CacheLayoutType::Entries,
        count: 8,
        ecc: false,
        sectored: CacheSectored::No,
    },
    CacheDescriptor { // 0x77
        level: CacheLevel::L1,
        type_of_cache: CacheType::Code,
        size: CacheSize::Size16K,
        associativity: CacheAssociativity::Assoc4Way,
        layout: CacheLayoutType::ByteLines,
        count: 64,
        ecc: false,
        sectored: CacheSectored::Single,
    },
    CacheDescriptor { // 0x78
        level: CacheLevel::L2,
        type_of_cache: CacheType::CodeAndData,
        size: CacheSize::Size1024K,
        associativity: CacheAssociativity::Assoc4Way,
        layout: CacheLayoutType::ByteLines,
        count: 64,
        ecc: false,
        sectored: CacheSectored::No,
    },
    CacheDescriptor { // 0x79
        level: CacheLevel::L2,
        type_of_cache: CacheType::CodeAndData,
        size: CacheSize::Size128K,
        associativity: CacheAssociativity::Assoc8Way,
        layout: CacheLayoutType::ByteLines,
        count: 64,
        ecc: false,
        sectored: CacheSectored::Dual,
    },
    CacheDescriptor { // 0x7A
        level: CacheLevel::L2,
        type_of_cache: CacheType::CodeAndData,
        size: CacheSize::Size256K,
        associativity: CacheAssociativity::Assoc8Way,
        layout: CacheLayoutType::ByteLines,
        count: 64,
        ecc: false,
        sectored: CacheSectored::Dual,
    },
    CacheDescriptor { // 0x7B
        level: CacheLevel::L2,
        type_of_cache: CacheType::CodeAndData,
        size: CacheSize::Size512K,
        associativity: CacheAssociativity::Assoc8Way,
        layout: CacheLayoutType::ByteLines,
        count: 64,
        ecc: false,
        sectored: CacheSectored::Dual,
    },
    CacheDescriptor { // 0x7C
        level: CacheLevel::L2,
        type_of_cache: CacheType::CodeAndData,
        size: CacheSize::Size1024K,
        associativity: CacheAssociativity::Assoc8Way,
        layout: CacheLayoutType::ByteLines,
        count: 64,
        ecc: false,
        sectored: CacheSectored::Dual,
    },
    CacheDescriptor { // 0x7D
        level: CacheLevel::L2,
        type_of_cache: CacheType::CodeAndData,
        size: CacheSize::Size2048K,
        associativity: CacheAssociativity::Assoc8Way,
        layout: CacheLayoutType::ByteLines,
        count: 64,
        ecc: false,
        sectored: CacheSectored::No,
    },
    CacheDescriptor { // 0x7E
        level: CacheLevel::L2,
        type_of_cache: CacheType::CodeAndData,
        size: CacheSize::Size256K,
        associativity: CacheAssociativity::Assoc8Way,
        layout: CacheLayoutType::ByteLines,
        count: 128,
        ecc: false,
        sectored: CacheSectored::Single,
    },
    CacheDescriptor { // 0x7F
        level: CacheLevel::L2,
        type_of_cache: CacheType::CodeAndData,
        size: CacheSize::Size512K,
        associativity: CacheAssociativity::Assoc2Way,
        layout: CacheLayoutType::ByteLines,
        count: 64,
        ecc: false,
        sectored: CacheSectored::No,
    },
    CacheDescriptor { // 0x80
        level: CacheLevel::L2,
        type_of_cache: CacheType::CodeAndData,
        size: CacheSize::Size512K,
        associativity: CacheAssociativity::Assoc8Way,
        layout: CacheLayoutType::ByteLines,
        count: 64,
        ecc: false,
        sectored: CacheSectored::No,
    },
    CacheDescriptor { // 0x81
        level: CacheLevel::L2,
        type_of_cache: CacheType::CodeAndData,
        size: CacheSize::Size128K,
        associativity: CacheAssociativity::Assoc8Way,
        layout: CacheLayoutType::ByteLines,
        count: 32,
        ecc: false,
        sectored: CacheSectored::No,
    },
    CacheDescriptor { // 0x82
        level: CacheLevel::L2,
        type_of_cache: CacheType::CodeAndData,
        size: CacheSize::Size256K,
        associativity: CacheAssociativity::Assoc8Way,
        layout: CacheLayoutType::ByteLines,
        count: 32,
        ecc: false,
        sectored: CacheSectored::No,
    },
    CacheDescriptor { // 0x83
        level: CacheLevel::L2,
        type_of_cache: CacheType::CodeAndData,
        size: CacheSize::Size512K,
        associativity: CacheAssociativity::Assoc8Way,
        layout: CacheLayoutType::ByteLines,
        count: 32,
        ecc: false,
        sectored: CacheSectored::No,
    },
    CacheDescriptor { // 0x84
        level: CacheLevel::L2,
        type_of_cache: CacheType::CodeAndData,
        size: CacheSize::Size1024K,
        associativity: CacheAssociativity::Assoc8Way,
        layout: CacheLayoutType::ByteLines,
        count: 32,
        ecc: false,
        sectored: CacheSectored::No,
    },
    CacheDescriptor { // 0x85
        level: CacheLevel::L2,
        type_of_cache: CacheType::CodeAndData,
        size: CacheSize::Size2048K,
        associativity: CacheAssociativity::Assoc8Way,
        layout: CacheLayoutType::ByteLines,
        count: 32,
        ecc: false,
        sectored: CacheSectored::No,
    },
    CacheDescriptor { // 0x86
        level: CacheLevel::L2,
        type_of_cache: CacheType::CodeAndData,
        size: CacheSize::Size512K,
        associativity: CacheAssociativity::Assoc4Way,
        layout: CacheLayoutType::ByteLines,
        count: 64,
        ecc: false,
        sectored: CacheSectored::No,
    },
    CacheDescriptor { // 0x87
        level: CacheLevel::L2,
        type_of_cache: CacheType::CodeAndData,
        size: CacheSize::Size1024K,
        associativity: CacheAssociativity::Assoc8Way,
        layout: CacheLayoutType::ByteLines,
        count: 64,
        ecc: false,
        sectored: CacheSectored::No,
    },
    CacheDescriptor { // 0x88
        level: CacheLevel::L3,
        type_of_cache: CacheType::CodeAndData,
        size: CacheSize::Size2048K,
        associativity: CacheAssociativity::Assoc4Way,
        layout: CacheLayoutType::ByteLines,
        count: 64,
        ecc: false,
        sectored: CacheSectored::No,
    },
    CacheDescriptor { // 0x89
        level: CacheLevel::L3,
        type_of_cache: CacheType::CodeAndData,
        size: CacheSize::Size4096K,
        associativity: CacheAssociativity::Assoc4Way,
        layout: CacheLayoutType::ByteLines,
        count: 64,
        ecc: false,
        sectored: CacheSectored::No,
    },
    CacheDescriptor { // 0x8A
        level: CacheLevel::L3,
        type_of_cache: CacheType::CodeAndData,
        size: CacheSize::Size8192K,
        associativity: CacheAssociativity::Assoc4Way,
        layout: CacheLayoutType::ByteLines,
        count: 64,
        ecc: false,
        sectored: CacheSectored::No,
    },
    CacheDescriptor { // 0x8B (UNKNOWN)
        level: CacheLevel::Unknown,
        type_of_cache: CacheType::Unknown,
        size: CacheSize::Unknown,
        associativity: CacheAssociativity::Unknown,
        layout: CacheLayoutType::Unknown,
        count: 0,
        ecc: false,
        sectored: CacheSectored::No,
    },
    CacheDescriptor { // 0x8C (UNKNOWN)
        level: CacheLevel::Unknown,
        type_of_cache: CacheType::Unknown,
        size: CacheSize::Unknown,
        associativity: CacheAssociativity::Unknown,
        layout: CacheLayoutType::Unknown,
        count: 0,
        ecc: false,
        sectored: CacheSectored::No,
    },
    CacheDescriptor { // 0x8D
        level: CacheLevel::L3,
        type_of_cache: CacheType::CodeAndData,
        size: CacheSize::Size3072K,
        associativity: CacheAssociativity::Assoc12Way,
        layout: CacheLayoutType::ByteLines,
        count: 128,
        ecc: false,
        sectored: CacheSectored::No,
    },
    CacheDescriptor { // 0x8E (UNKNOWN)
        level: CacheLevel::Unknown,
        type_of_cache: CacheType::Unknown,
        size: CacheSize::Unknown,
        associativity: CacheAssociativity::Unknown,
        layout: CacheLayoutType::Unknown,
        count: 0,
        ecc: false,
        sectored: CacheSectored::No,
    },
    CacheDescriptor { // 0x8F (UNKNOWN)
        level: CacheLevel::Unknown,
        type_of_cache: CacheType::Unknown,
        size: CacheSize::Unknown,
        associativity: CacheAssociativity::Unknown,
        layout: CacheLayoutType::Unknown,
        count: 0,
        ecc: false,
        sectored: CacheSectored::No,
    },
    CacheDescriptor { // 0x90
        level: CacheLevel::TLB,
        type_of_cache: CacheType::Code,
        size: CacheSize::Size4K256M,
        associativity: CacheAssociativity::Fully,
        layout: CacheLayoutType::Entries,
        count: 64,
        ecc: false,
        sectored: CacheSectored::No,
    },
    CacheDescriptor { // 0x91 (UNKNOWN)
        level: CacheLevel::Unknown,
        type_of_cache: CacheType::Unknown,
        size: CacheSize::Unknown,
        associativity: CacheAssociativity::Unknown,
        layout: CacheLayoutType::Unknown,
        count: 0,
        ecc: false,
        sectored: CacheSectored::No,
    },
    CacheDescriptor { // 0x92 (UNKNOWN)
        level: CacheLevel::Unknown,
        type_of_cache: CacheType::Unknown,
        size: CacheSize::Unknown,
        associativity: CacheAssociativity::Unknown,
        layout: CacheLayoutType::Unknown,
        count: 0,
        ecc: false,
        sectored: CacheSectored::No,
    },
    CacheDescriptor { // 0x93 (UNKNOWN)
        level: CacheLevel::Unknown,
        type_of_cache: CacheType::Unknown,
        size: CacheSize::Unknown,
        associativity: CacheAssociativity::Unknown,
        layout: CacheLayoutType::Unknown,
        count: 0,
        ecc: false,
        sectored: CacheSectored::No,
    },
    CacheDescriptor { // 0x94 (UNKNOWN)
        level: CacheLevel::Unknown,
        type_of_cache: CacheType::Unknown,
        size: CacheSize::Unknown,
        associativity: CacheAssociativity::Unknown,
        layout: CacheLayoutType::Unknown,
        count: 0,
        ecc: false,
        sectored: CacheSectored::No,
    },
    CacheDescriptor { // 0x95 (UNKNOWN)
        level: CacheLevel::Unknown,
        type_of_cache: CacheType::Unknown,
        size: CacheSize::Unknown,
        associativity: CacheAssociativity::Unknown,
        layout: CacheLayoutType::Unknown,
        count: 0,
        ecc: false,
        sectored: CacheSectored::No,
    },
    CacheDescriptor { // 0x96
        level: CacheLevel::L1TLB,
        type_of_cache: CacheType::Data,
        size: CacheSize::Size4K256M,
        associativity: CacheAssociativity::Fully,
        layout: CacheLayoutType::Entries,
        count:32,
        ecc: false,
        sectored: CacheSectored::No,
    },
    CacheDescriptor { // 0x97 (UNKNOWN)
        level: CacheLevel::Unknown,
        type_of_cache: CacheType::Unknown,
        size: CacheSize::Unknown,
        associativity: CacheAssociativity::Unknown,
        layout: CacheLayoutType::Unknown,
        count: 0,
        ecc: false,
        sectored: CacheSectored::No,
    },
    CacheDescriptor { // 0x98 (UNKNOWN)
        level: CacheLevel::Unknown,
        type_of_cache: CacheType::Unknown,
        size: CacheSize::Unknown,
        associativity: CacheAssociativity::Unknown,
        layout: CacheLayoutType::Unknown,
        count: 0,
        ecc: false,
        sectored: CacheSectored::No,
    },
    CacheDescriptor { // 0x99 (UNKNOWN)
        level: CacheLevel::Unknown,
        type_of_cache: CacheType::Unknown,
        size: CacheSize::Unknown,
        associativity: CacheAssociativity::Unknown,
        layout: CacheLayoutType::Unknown,
        count: 0,
        ecc: false,
        sectored: CacheSectored::No,
    },
    CacheDescriptor { // 0x9A (UNKNOWN)
        level: CacheLevel::Unknown,
        type_of_cache: CacheType::Unknown,
        size: CacheSize::Unknown,
        associativity: CacheAssociativity::Unknown,
        layout: CacheLayoutType::Unknown,
        count: 0,
        ecc: false,
        sectored: CacheSectored::No,
    },
    CacheDescriptor { // 0x9B
        level: CacheLevel::L2TLB,
        type_of_cache: CacheType::Data,
        size: CacheSize::Size4K256M,
        associativity: CacheAssociativity::Fully,
        layout: CacheLayoutType::Entries,
        count:96,
        ecc: false,
        sectored: CacheSectored::No,
    },
    CacheDescriptor { // 0x9C (UNKNOWN)
        level: CacheLevel::Unknown,
        type_of_cache: CacheType::Unknown,
        size: CacheSize::Unknown,
        associativity: CacheAssociativity::Unknown,
        layout: CacheLayoutType::Unknown,
        count: 0,
        ecc: false,
        sectored: CacheSectored::No,
    },
    CacheDescriptor { // 0x9D (UNKNOWN)
        level: CacheLevel::Unknown,
        type_of_cache: CacheType::Unknown,
        size: CacheSize::Unknown,
        associativity: CacheAssociativity::Unknown,
        layout: CacheLayoutType::Unknown,
        count: 0,
        ecc: false,
        sectored: CacheSectored::No,
    },
    CacheDescriptor { // 0x9E (UNKNOWN)
        level: CacheLevel::Unknown,
        type_of_cache: CacheType::Unknown,
        size: CacheSize::Unknown,
        associativity: CacheAssociativity::Unknown,
        layout: CacheLayoutType::Unknown,
        count: 0,
        ecc: false,
        sectored: CacheSectored::No,
    },
    CacheDescriptor { // 0x9F (UNKNOWN)
        level: CacheLevel::Unknown,
        type_of_cache: CacheType::Unknown,
        size: CacheSize::Unknown,
        associativity: CacheAssociativity::Unknown,
        layout: CacheLayoutType::Unknown,
        count: 0,
        ecc: false,
        sectored: CacheSectored::No,
    },
    CacheDescriptor { // 0xA0
        level: CacheLevel::TLB,
        type_of_cache: CacheType::Data,
        size: CacheSize::Size4K,
        associativity: CacheAssociativity::Fully,
        layout: CacheLayoutType::Entries,
        count:96,
        ecc: false,
        sectored: CacheSectored::No,
    },
    CacheDescriptor { // 0xA1 (UNKNOWN)
        level: CacheLevel::Unknown,
        type_of_cache: CacheType::Unknown,
        size: CacheSize::Unknown,
        associativity: CacheAssociativity::Unknown,
        layout: CacheLayoutType::Unknown,
        count: 0,
        ecc: false,
        sectored: CacheSectored::No,
    },
    CacheDescriptor { // 0xA2 (UNKNOWN)
        level: CacheLevel::Unknown,
        type_of_cache: CacheType::Unknown,
        size: CacheSize::Unknown,
        associativity: CacheAssociativity::Unknown,
        layout: CacheLayoutType::Unknown,
        count: 0,
        ecc: false,
        sectored: CacheSectored::No,
    },
    CacheDescriptor { // 0xA3 (UNKNOWN)
        level: CacheLevel::Unknown,
        type_of_cache: CacheType::Unknown,
        size: CacheSize::Unknown,
        associativity: CacheAssociativity::Unknown,
        layout: CacheLayoutType::Unknown,
        count: 0,
        ecc: false,
        sectored: CacheSectored::No,
    },
    CacheDescriptor { // 0xA4 (UNKNOWN)
        level: CacheLevel::Unknown,
        type_of_cache: CacheType::Unknown,
        size: CacheSize::Unknown,
        associativity: CacheAssociativity::Unknown,
        layout: CacheLayoutType::Unknown,
        count: 0,
        ecc: false,
        sectored: CacheSectored::No,
    },
    CacheDescriptor { // 0xA5 (UNKNOWN)
        level: CacheLevel::Unknown,
        type_of_cache: CacheType::Unknown,
        size: CacheSize::Unknown,
        associativity: CacheAssociativity::Unknown,
        layout: CacheLayoutType::Unknown,
        count: 0,
        ecc: false,
        sectored: CacheSectored::No,
    },
    CacheDescriptor { // 0xA6 (UNKNOWN)
        level: CacheLevel::Unknown,
        type_of_cache: CacheType::Unknown,
        size: CacheSize::Unknown,
        associativity: CacheAssociativity::Unknown,
        layout: CacheLayoutType::Unknown,
        count: 0,
        ecc: false,
        sectored: CacheSectored::No,
    },
    CacheDescriptor { // 0xA7 (UNKNOWN)
        level: CacheLevel::Unknown,
        type_of_cache: CacheType::Unknown,
        size: CacheSize::Unknown,
        associativity: CacheAssociativity::Unknown,
        layout: CacheLayoutType::Unknown,
        count: 0,
        ecc: false,
        sectored: CacheSectored::No,
    },
    CacheDescriptor { // 0xA8 (UNKNOWN)
        level: CacheLevel::Unknown,
        type_of_cache: CacheType::Unknown,
        size: CacheSize::Unknown,
        associativity: CacheAssociativity::Unknown,
        layout: CacheLayoutType::Unknown,
        count: 0,
        ecc: false,
        sectored: CacheSectored::No,
    },
    CacheDescriptor { // 0xA9 (UNKNOWN)
        level: CacheLevel::Unknown,
        type_of_cache: CacheType::Unknown,
        size: CacheSize::Unknown,
        associativity: CacheAssociativity::Unknown,
        layout: CacheLayoutType::Unknown,
        count: 0,
        ecc: false,
        sectored: CacheSectored::No,
    },
    CacheDescriptor { // 0xAA (UNKNOWN)
        level: CacheLevel::Unknown,
        type_of_cache: CacheType::Unknown,
        size: CacheSize::Unknown,
        associativity: CacheAssociativity::Unknown,
        layout: CacheLayoutType::Unknown,
        count: 0,
        ecc: false,
        sectored: CacheSectored::No,
    },
    CacheDescriptor { // 0xAB (UNKNOWN)
        level: CacheLevel::Unknown,
        type_of_cache: CacheType::Unknown,
        size: CacheSize::Unknown,
        associativity: CacheAssociativity::Unknown,
        layout: CacheLayoutType::Unknown,
        count: 0,
        ecc: false,
        sectored: CacheSectored::No,
    },
    CacheDescriptor { // 0xAC (UNKNOWN)
        level: CacheLevel::Unknown,
        type_of_cache: CacheType::Unknown,
        size: CacheSize::Unknown,
        associativity: CacheAssociativity::Unknown,
        layout: CacheLayoutType::Unknown,
        count: 0,
        ecc: false,
        sectored: CacheSectored::No,
    },
    CacheDescriptor { // 0xAD (UNKNOWN)
        level: CacheLevel::Unknown,
        type_of_cache: CacheType::Unknown,
        size: CacheSize::Unknown,
        associativity: CacheAssociativity::Unknown,
        layout: CacheLayoutType::Unknown,
        count: 0,
        ecc: false,
        sectored: CacheSectored::No,
    },
    CacheDescriptor { // 0xAE (UNKNOWN)
        level: CacheLevel::Unknown,
        type_of_cache: CacheType::Unknown,
        size: CacheSize::Unknown,
        associativity: CacheAssociativity::Unknown,
        layout: CacheLayoutType::Unknown,
        count: 0,
        ecc: false,
        sectored: CacheSectored::No,
    },
    CacheDescriptor { // 0xAF (UNKNOWN)
        level: CacheLevel::Unknown,
        type_of_cache: CacheType::Unknown,
        size: CacheSize::Unknown,
        associativity: CacheAssociativity::Unknown,
        layout: CacheLayoutType::Unknown,
        count: 0,
        ecc: false,
        sectored: CacheSectored::No,
    },
    CacheDescriptor { // 0xB0
        level: CacheLevel::TLB,
        type_of_cache: CacheType::Code,
        size: CacheSize::Size4K,
        associativity: CacheAssociativity::Assoc4Way,
        layout: CacheLayoutType::Entries,
        count: 128,
        ecc: false,
        sectored: CacheSectored::No,
    },
    CacheDescriptor { // 0xB1
        level: CacheLevel::TLB,
        type_of_cache: CacheType::Code,
        size: CacheSize::Size2M,
        associativity: CacheAssociativity::Assoc4Way,
        layout: CacheLayoutType::Entries,
        count: 8,
        ecc: false,
        sectored: CacheSectored::No,
    },
    CacheDescriptor { // 0xB2
        level: CacheLevel::TLB,
        type_of_cache: CacheType::Code,
        size: CacheSize::Size4K,
        associativity: CacheAssociativity::Assoc4Way,
        layout: CacheLayoutType::Entries,
        count: 64,
        ecc: false,
        sectored: CacheSectored::No,
    },
    CacheDescriptor { // 0xB3
        level: CacheLevel::TLB,
        type_of_cache: CacheType::Data,
        size: CacheSize::Size4K,
        associativity: CacheAssociativity::Assoc4Way,
        layout: CacheLayoutType::Entries,
        count: 128,
        ecc: false,
        sectored: CacheSectored::No,
    },
    CacheDescriptor { // 0xB4
        level: CacheLevel::TLB,
        type_of_cache: CacheType::Data,
        size: CacheSize::Size4K,
        associativity: CacheAssociativity::Assoc4Way,
        layout: CacheLayoutType::Entries,
        count: 256,
        ecc: false,
        sectored: CacheSectored::No,
    },
    CacheDescriptor { // 0xB5
        level: CacheLevel::TLB,
        type_of_cache: CacheType::Code,
        size: CacheSize::Size4K,
        associativity: CacheAssociativity::Assoc8Way,
        layout: CacheLayoutType::Entries,
        count: 64,
        ecc: false,
        sectored: CacheSectored::No,
    },
    CacheDescriptor { // 0xB6
        level: CacheLevel::TLB,
        type_of_cache: CacheType::Code,
        size: CacheSize::Size4K,
        associativity: CacheAssociativity::Assoc8Way,
        layout: CacheLayoutType::Entries,
        count: 128,
        ecc: false,
        sectored: CacheSectored::No,
    },
    CacheDescriptor { // 0xB7 (UNKNOWN)
        level: CacheLevel::Unknown,
        type_of_cache: CacheType::Unknown,
        size: CacheSize::Unknown,
        associativity: CacheAssociativity::Unknown,
        layout: CacheLayoutType::Unknown,
        count: 0,
        ecc: false,
        sectored: CacheSectored::No,
    },
    CacheDescriptor { // 0xB8 (UNKNOWN)
        level: CacheLevel::Unknown,
        type_of_cache: CacheType::Unknown,
        size: CacheSize::Unknown,
        associativity: CacheAssociativity::Unknown,
        layout: CacheLayoutType::Unknown,
        count: 0,
        ecc: false,
        sectored: CacheSectored::No,
    },
    CacheDescriptor { // 0xB9 (UNKNOWN)
        level: CacheLevel::Unknown,
        type_of_cache: CacheType::Unknown,
        size: CacheSize::Unknown,
        associativity: CacheAssociativity::Unknown,
        layout: CacheLayoutType::Unknown,
        count: 0,
        ecc: false,
        sectored: CacheSectored::No,
    },
    CacheDescriptor { // 0xBA
        level: CacheLevel::TLB,
        type_of_cache: CacheType::Data,
        size: CacheSize::Size4K,
        associativity: CacheAssociativity::Assoc4Way,
        layout: CacheLayoutType::Entries,
        count: 64,
        ecc: false,
        sectored: CacheSectored::No,
    },
    CacheDescriptor { // 0xBB (UNKNOWN)
        level: CacheLevel::Unknown,
        type_of_cache: CacheType::Unknown,
        size: CacheSize::Unknown,
        associativity: CacheAssociativity::Unknown,
        layout: CacheLayoutType::Unknown,
        count: 0,
        ecc: false,
        sectored: CacheSectored::No,
    },
    CacheDescriptor { // 0xBC (UNKNOWN)
        level: CacheLevel::Unknown,
        type_of_cache: CacheType::Unknown,
        size: CacheSize::Unknown,
        associativity: CacheAssociativity::Unknown,
        layout: CacheLayoutType::Unknown,
        count: 0,
        ecc: false,
        sectored: CacheSectored::No,
    },
    CacheDescriptor { // 0xBD (UNKNOWN)
        level: CacheLevel::Unknown,
        type_of_cache: CacheType::Unknown,
        size: CacheSize::Unknown,
        associativity: CacheAssociativity::Unknown,
        layout: CacheLayoutType::Unknown,
        count: 0,
        ecc: false,
        sectored: CacheSectored::No,
    },
    CacheDescriptor { // 0xBE (UNKNOWN)
        level: CacheLevel::Unknown,
        type_of_cache: CacheType::Unknown,
        size: CacheSize::Unknown,
        associativity: CacheAssociativity::Unknown,
        layout: CacheLayoutType::Unknown,
        count: 0,
        ecc: false,
        sectored: CacheSectored::No,
    },
    CacheDescriptor { // 0xBF (UNKNOWN)
        level: CacheLevel::Unknown,
        type_of_cache: CacheType::Unknown,
        size: CacheSize::Unknown,
        associativity: CacheAssociativity::Unknown,
        layout: CacheLayoutType::Unknown,
        count: 0,
        ecc: false,
        sectored: CacheSectored::No,
    },
    CacheDescriptor { // 0xC0
        level: CacheLevel::TLB,
        type_of_cache: CacheType::Data,
        size: CacheSize::Size4K4M,
        associativity: CacheAssociativity::Assoc4Way,
        layout: CacheLayoutType::Entries,
        count: 8,
        ecc: false,
        sectored: CacheSectored::No,
    },
    CacheDescriptor { // 0xC1
        level: CacheLevel::L2TLB,
        type_of_cache: CacheType::CodeAndData,
        size: CacheSize::Size4K2M,
        associativity: CacheAssociativity::Assoc8Way,
        layout: CacheLayoutType::Entries,
        count: 1024,
        ecc: false,
        sectored: CacheSectored::No,
    },
    CacheDescriptor { // 0xC2
        level: CacheLevel::TLB,
        type_of_cache: CacheType::Data,
        size: CacheSize::Size2M4M,
        associativity: CacheAssociativity::Assoc4Way,
        layout: CacheLayoutType::Entries,
        count: 16,
        ecc: false,
        sectored: CacheSectored::No,
    },
    CacheDescriptor { // 0xC3
        level: CacheLevel::L2,
        type_of_cache: CacheType::Code,
        size: CacheSize::Size4K2M,
        associativity: CacheAssociativity::Assoc6Way,
        layout: CacheLayoutType::Entries,
        count: 16,
        ecc: false,
        sectored: CacheSectored::No,
    },
    CacheDescriptor { // 0xC4
        level: CacheLevel::TLB,
        type_of_cache: CacheType::Data,
        size: CacheSize::Size2M4M,
        associativity: CacheAssociativity::Assoc4Way,
        layout: CacheLayoutType::Entries,
        count: 32,
        ecc: false,
        sectored: CacheSectored::No,
    },
    CacheDescriptor { // 0xC5 (UNKNOWN)
        level: CacheLevel::Unknown,
        type_of_cache: CacheType::Unknown,
        size: CacheSize::Unknown,
        associativity: CacheAssociativity::Unknown,
        layout: CacheLayoutType::Unknown,
        count: 0,
        ecc: false,
        sectored: CacheSectored::No,
    },
    CacheDescriptor { // 0xC6 (UNKNOWN)
        level: CacheLevel::Unknown,
        type_of_cache: CacheType::Unknown,
        size: CacheSize::Unknown,
        associativity: CacheAssociativity::Unknown,
        layout: CacheLayoutType::Unknown,
        count: 0,
        ecc: false,
        sectored: CacheSectored::No,
    },
    CacheDescriptor { // 0xC7 (UNKNOWN)
        level: CacheLevel::Unknown,
        type_of_cache: CacheType::Unknown,
        size: CacheSize::Unknown,
        associativity: CacheAssociativity::Unknown,
        layout: CacheLayoutType::Unknown,
        count: 0,
        ecc: false,
        sectored: CacheSectored::No,
    },
    CacheDescriptor { // 0xC8 (UNKNOWN)
        level: CacheLevel::Unknown,
        type_of_cache: CacheType::Unknown,
        size: CacheSize::Unknown,
        associativity: CacheAssociativity::Unknown,
        layout: CacheLayoutType::Unknown,
        count: 0,
        ecc: false,
        sectored: CacheSectored::No,
    },
    CacheDescriptor { // 0xC9 (UNKNOWN)
        level: CacheLevel::Unknown,
        type_of_cache: CacheType::Unknown,
        size: CacheSize::Unknown,
        associativity: CacheAssociativity::Unknown,
        layout: CacheLayoutType::Unknown,
        count: 0,
        ecc: false,
        sectored: CacheSectored::No,
    },
    CacheDescriptor { // 0xCA
        level: CacheLevel::L2TLB,
        type_of_cache: CacheType::CodeAndData,
        size: CacheSize::Size4K,
        associativity: CacheAssociativity::Assoc4Way,
        layout: CacheLayoutType::Entries,
        count: 512,
        ecc: false,
        sectored: CacheSectored::No,
    },
    CacheDescriptor { // 0xCB (UNKNOWN)
        level: CacheLevel::Unknown,
        type_of_cache: CacheType::Unknown,
        size: CacheSize::Unknown,
        associativity: CacheAssociativity::Unknown,
        layout: CacheLayoutType::Unknown,
        count: 0,
        ecc: false,
        sectored: CacheSectored::No,
    },
    CacheDescriptor { // 0xCC (UNKNOWN)
        level: CacheLevel::Unknown,
        type_of_cache: CacheType::Unknown,
        size: CacheSize::Unknown,
        associativity: CacheAssociativity::Unknown,
        layout: CacheLayoutType::Unknown,
        count: 0,
        ecc: false,
        sectored: CacheSectored::No,
    },
    CacheDescriptor { // 0xCD (UNKNOWN)
        level: CacheLevel::Unknown,
        type_of_cache: CacheType::Unknown,
        size: CacheSize::Unknown,
        associativity: CacheAssociativity::Unknown,
        layout: CacheLayoutType::Unknown,
        count: 0,
        ecc: false,
        sectored: CacheSectored::No,
    },
    CacheDescriptor { // 0xCE (UNKNOWN)
        level: CacheLevel::Unknown,
        type_of_cache: CacheType::Unknown,
        size: CacheSize::Unknown,
        associativity: CacheAssociativity::Unknown,
        layout: CacheLayoutType::Unknown,
        count: 0,
        ecc: false,
        sectored: CacheSectored::No,
    },
    CacheDescriptor { // 0xCF (UNKNOWN)
        level: CacheLevel::Unknown,
        type_of_cache: CacheType::Unknown,
        size: CacheSize::Unknown,
        associativity: CacheAssociativity::Unknown,
        layout: CacheLayoutType::Unknown,
        count: 0,
        ecc: false,
        sectored: CacheSectored::No,
    },
    CacheDescriptor { // 0xD0
        level: CacheLevel::L3,
        type_of_cache: CacheType::CodeAndData,
        size: CacheSize::Size512K,
        associativity: CacheAssociativity::Assoc4Way,
        layout: CacheLayoutType::ByteLines,
        count: 64,
        ecc: false,
        sectored: CacheSectored::No,
    },
    CacheDescriptor { // 0xD1
        level: CacheLevel::L3,
        type_of_cache: CacheType::CodeAndData,
        size: CacheSize::Size1024K,
        associativity: CacheAssociativity::Assoc4Way,
        layout: CacheLayoutType::ByteLines,
        count: 64,
        ecc: false,
        sectored: CacheSectored::No,
    },
    CacheDescriptor { // 0xD2
        level: CacheLevel::L3,
        type_of_cache: CacheType::CodeAndData,
        size: CacheSize::Size2048K,
        associativity: CacheAssociativity::Assoc4Way,
        layout: CacheLayoutType::ByteLines,
        count: 64,
        ecc: false,
        sectored: CacheSectored::No,
    },
    CacheDescriptor { // 0xD3 (UNKNOWN)
        level: CacheLevel::Unknown,
        type_of_cache: CacheType::Unknown,
        size: CacheSize::Unknown,
        associativity: CacheAssociativity::Unknown,
        layout: CacheLayoutType::Unknown,
        count: 0,
        ecc: false,
        sectored: CacheSectored::No,
    },
    CacheDescriptor { // 0xD4 (UNKNOWN)
        level: CacheLevel::Unknown,
        type_of_cache: CacheType::Unknown,
        size: CacheSize::Unknown,
        associativity: CacheAssociativity::Unknown,
        layout: CacheLayoutType::Unknown,
        count: 0,
        ecc: false,
        sectored: CacheSectored::No,
    },
    CacheDescriptor { // 0xD5 (UNKNOWN)
        level: CacheLevel::Unknown,
        type_of_cache: CacheType::Unknown,
        size: CacheSize::Unknown,
        associativity: CacheAssociativity::Unknown,
        layout: CacheLayoutType::Unknown,
        count: 0,
        ecc: false,
        sectored: CacheSectored::No,
    },
    CacheDescriptor { // 0xD6
        level: CacheLevel::L3,
        type_of_cache: CacheType::CodeAndData,
        size: CacheSize::Size1024K,
        associativity: CacheAssociativity::Assoc8Way,
        layout: CacheLayoutType::ByteLines,
        count: 64,
        ecc: false,
        sectored: CacheSectored::No,
    },
    CacheDescriptor { // 0xD7
        level: CacheLevel::L3,
        type_of_cache: CacheType::CodeAndData,
        size: CacheSize::Size2048K,
        associativity: CacheAssociativity::Assoc8Way,
        layout: CacheLayoutType::ByteLines,
        count: 64,
        ecc: false,
        sectored: CacheSectored::No,
    },
    CacheDescriptor { // 0xD8
        level: CacheLevel::L3,
        type_of_cache: CacheType::CodeAndData,
        size: CacheSize::Size4096K,
        associativity: CacheAssociativity::Assoc8Way,
        layout: CacheLayoutType::ByteLines,
        count: 64,
        ecc: false,
        sectored: CacheSectored::No,
    },
    CacheDescriptor { // 0xD9 (UNKNOWN)
        level: CacheLevel::Unknown,
        type_of_cache: CacheType::Unknown,
        size: CacheSize::Unknown,
        associativity: CacheAssociativity::Unknown,
        layout: CacheLayoutType::Unknown,
        count: 0,
        ecc: false,
        sectored: CacheSectored::No,
    },
    CacheDescriptor { // 0xDA (UNKNOWN)
        level: CacheLevel::Unknown,
        type_of_cache: CacheType::Unknown,
        size: CacheSize::Unknown,
        associativity: CacheAssociativity::Unknown,
        layout: CacheLayoutType::Unknown,
        count: 0,
        ecc: false,
        sectored: CacheSectored::No,
    },
    CacheDescriptor { // 0xDB (UNKNOWN)
        level: CacheLevel::Unknown,
        type_of_cache: CacheType::Unknown,
        size: CacheSize::Unknown,
        associativity: CacheAssociativity::Unknown,
        layout: CacheLayoutType::Unknown,
        count: 0,
        ecc: false,
        sectored: CacheSectored::No,
    },
    CacheDescriptor { // 0xDC
        level: CacheLevel::L3,
        type_of_cache: CacheType::CodeAndData,
        size: CacheSize::Size1536K,
        associativity: CacheAssociativity::Assoc12Way,
        layout: CacheLayoutType::ByteLines,
        count: 64,
        ecc: false,
        sectored: CacheSectored::No,
    },
    CacheDescriptor { // 0xDD
        level: CacheLevel::L3,
        type_of_cache: CacheType::CodeAndData,
        size: CacheSize::Size3072K,
        associativity: CacheAssociativity::Assoc12Way,
        layout: CacheLayoutType::ByteLines,
        count: 64,
        ecc: false,
        sectored: CacheSectored::No,
    },
    CacheDescriptor { // 0xDE
        level: CacheLevel::L3,
        type_of_cache: CacheType::CodeAndData,
        size: CacheSize::Size6144K,
        associativity: CacheAssociativity::Assoc12Way,
        layout: CacheLayoutType::ByteLines,
        count: 64,
        ecc: false,
        sectored: CacheSectored::No,
    },
    CacheDescriptor { // 0xDF (UNKNOWN)
        level: CacheLevel::Unknown,
        type_of_cache: CacheType::Unknown,
        size: CacheSize::Unknown,
        associativity: CacheAssociativity::Unknown,
        layout: CacheLayoutType::Unknown,
        count: 0,
        ecc: false,
        sectored: CacheSectored::No,
    },
    CacheDescriptor { // 0xE0 (UNKNOWN)
        level: CacheLevel::Unknown,
        type_of_cache: CacheType::Unknown,
        size: CacheSize::Unknown,
        associativity: CacheAssociativity::Unknown,
        layout: CacheLayoutType::Unknown,
        count: 0,
        ecc: false,
        sectored: CacheSectored::No,
    },
    CacheDescriptor { // 0xE1 (UNKNOWN)
        level: CacheLevel::Unknown,
        type_of_cache: CacheType::Unknown,
        size: CacheSize::Unknown,
        associativity: CacheAssociativity::Unknown,
        layout: CacheLayoutType::Unknown,
        count: 0,
        ecc: false,
        sectored: CacheSectored::No,
    },
    CacheDescriptor { // 0xE2
        level: CacheLevel::L3,
        type_of_cache: CacheType::CodeAndData,
        size: CacheSize::Size2048K,
        associativity: CacheAssociativity::Assoc16Way,
        layout: CacheLayoutType::ByteLines,
        count: 64,
        ecc: false,
        sectored: CacheSectored::No,
    },
    CacheDescriptor { // 0xE3
        level: CacheLevel::L3,
        type_of_cache: CacheType::CodeAndData,
        size: CacheSize::Size4096K,
        associativity: CacheAssociativity::Assoc16Way,
        layout: CacheLayoutType::ByteLines,
        count: 64,
        ecc: false,
        sectored: CacheSectored::No,
    },
    CacheDescriptor { // 0xE4
        level: CacheLevel::L3,
        type_of_cache: CacheType::CodeAndData,
        size: CacheSize::Size8192K,
        associativity: CacheAssociativity::Assoc16Way,
        layout: CacheLayoutType::ByteLines,
        count: 64,
        ecc: false,
        sectored: CacheSectored::No,
    },
    CacheDescriptor { // 0xE5 (UNKNOWN)
        level: CacheLevel::Unknown,
        type_of_cache: CacheType::Unknown,
        size: CacheSize::Unknown,
        associativity: CacheAssociativity::Unknown,
        layout: CacheLayoutType::Unknown,
        count: 0,
        ecc: false,
        sectored: CacheSectored::No,
    },
    CacheDescriptor { // 0xE6 (UNKNOWN)
        level: CacheLevel::Unknown,
        type_of_cache: CacheType::Unknown,
        size: CacheSize::Unknown,
        associativity: CacheAssociativity::Unknown,
        layout: CacheLayoutType::Unknown,
        count: 0,
        ecc: false,
        sectored: CacheSectored::No,
    },
    CacheDescriptor { // 0xE7 (UNKNOWN)
        level: CacheLevel::Unknown,
        type_of_cache: CacheType::Unknown,
        size: CacheSize::Unknown,
        associativity: CacheAssociativity::Unknown,
        layout: CacheLayoutType::Unknown,
        count: 0,
        ecc: false,
        sectored: CacheSectored::No,
    },
    CacheDescriptor { // 0xE8 (UNKNOWN)
        level: CacheLevel::Unknown,
        type_of_cache: CacheType::Unknown,
        size: CacheSize::Unknown,
        associativity: CacheAssociativity::Unknown,
        layout: CacheLayoutType::Unknown,
        count: 0,
        ecc: false,
        sectored: CacheSectored::No,
    },
    CacheDescriptor { // 0xE9 (UNKNOWN)
        level: CacheLevel::Unknown,
        type_of_cache: CacheType::Unknown,
        size: CacheSize::Unknown,
        associativity: CacheAssociativity::Unknown,
        layout: CacheLayoutType::Unknown,
        count: 0,
        ecc: false,
        sectored: CacheSectored::No,
    },
    CacheDescriptor { // 0xEA
        level: CacheLevel::L3,
        type_of_cache: CacheType::CodeAndData,
        size: CacheSize::Size12288K,
        associativity: CacheAssociativity::Assoc24Way,
        layout: CacheLayoutType::ByteLines,
        count: 64,
        ecc: false,
        sectored: CacheSectored::No,
    },
    CacheDescriptor { // 0xEB
        level: CacheLevel::L3,
        type_of_cache: CacheType::CodeAndData,
        size: CacheSize::Size18432K,
        associativity: CacheAssociativity::Assoc24Way,
        layout: CacheLayoutType::ByteLines,
        count: 64,
        ecc: false,
        sectored: CacheSectored::No,
    },
    CacheDescriptor { // 0xEC
        level: CacheLevel::L3,
        type_of_cache: CacheType::CodeAndData,
        size: CacheSize::Size24576K,
        associativity: CacheAssociativity::Assoc24Way,
        layout: CacheLayoutType::ByteLines,
        count: 64,
        ecc: false,
        sectored: CacheSectored::No,
    },
    CacheDescriptor { // 0xED (Unknown)
        level: CacheLevel::Unknown,
        type_of_cache: CacheType::Unknown,
        size: CacheSize::Unknown,
        associativity: CacheAssociativity::Unknown,
        layout: CacheLayoutType::Unknown,
        count: 0,
        ecc: false,
        sectored: CacheSectored::No,
    },
    CacheDescriptor { // 0xEE (Unknown)
        level: CacheLevel::Unknown,
        type_of_cache: CacheType::Unknown,
        size: CacheSize::Unknown,
        associativity: CacheAssociativity::Unknown,
        layout: CacheLayoutType::Unknown,
        count: 0,
        ecc: false,
        sectored: CacheSectored::No,
    },
    CacheDescriptor { // 0xEF (Unknown)
        level: CacheLevel::Unknown,
        type_of_cache: CacheType::Unknown,
        size: CacheSize::Unknown,
        associativity: CacheAssociativity::Unknown,
        layout: CacheLayoutType::Unknown,
        count: 0,
        ecc: false,
        sectored: CacheSectored::No,
    },
    CacheDescriptor { // 0xF0 (Unknown)
        level: CacheLevel::Unknown,
        type_of_cache: CacheType::Unknown,
        size: CacheSize::Unknown,
        associativity: CacheAssociativity::Unknown,
        layout: CacheLayoutType::Unknown,
        count: 0,
        ecc: false,
        sectored: CacheSectored::No,
    },
    CacheDescriptor { // 0xF1 (Unknown)
        level: CacheLevel::Unknown,
        type_of_cache: CacheType::Unknown,
        size: CacheSize::Unknown,
        associativity: CacheAssociativity::Unknown,
        layout: CacheLayoutType::Unknown,
        count: 0,
        ecc: false,
        sectored: CacheSectored::No,
    },
    CacheDescriptor { // 0xF2 (Unknown)
        level: CacheLevel::Unknown,
        type_of_cache: CacheType::Unknown,
        size: CacheSize::Unknown,
        associativity: CacheAssociativity::Unknown,
        layout: CacheLayoutType::Unknown,
        count: 0,
        ecc: false,
        sectored: CacheSectored::No,
    },
    CacheDescriptor { // 0xF3 (Unknown)
        level: CacheLevel::Unknown,
        type_of_cache: CacheType::Unknown,
        size: CacheSize::Unknown,
        associativity: CacheAssociativity::Unknown,
        layout: CacheLayoutType::Unknown,
        count: 0,
        ecc: false,
        sectored: CacheSectored::No,
    },
    CacheDescriptor { // 0xF4 (Unknown)
        level: CacheLevel::Unknown,
        type_of_cache: CacheType::Unknown,
        size: CacheSize::Unknown,
        associativity: CacheAssociativity::Unknown,
        layout: CacheLayoutType::Unknown,
        count: 0,
        ecc: false,
        sectored: CacheSectored::No,
    },
    CacheDescriptor { // 0xF5 (Unknown)
        level: CacheLevel::Unknown,
        type_of_cache: CacheType::Unknown,
        size: CacheSize::Unknown,
        associativity: CacheAssociativity::Unknown,
        layout: CacheLayoutType::Unknown,
        count: 0,
        ecc: false,
        sectored: CacheSectored::No,
    },
    CacheDescriptor { // 0xF6 (Unknown)
        level: CacheLevel::Unknown,
        type_of_cache: CacheType::Unknown,
        size: CacheSize::Unknown,
        associativity: CacheAssociativity::Unknown,
        layout: CacheLayoutType::Unknown,
        count: 0,
        ecc: false,
        sectored: CacheSectored::No,
    },
    CacheDescriptor { // 0xF7 (Unknown)
        level: CacheLevel::Unknown,
        type_of_cache: CacheType::Unknown,
        size: CacheSize::Unknown,
        associativity: CacheAssociativity::Unknown,
        layout: CacheLayoutType::Unknown,
        count: 0,
        ecc: false,
        sectored: CacheSectored::No,
    },
    CacheDescriptor { // 0xF8 (Unknown)
        level: CacheLevel::Unknown,
        type_of_cache: CacheType::Unknown,
        size: CacheSize::Unknown,
        associativity: CacheAssociativity::Unknown,
        layout: CacheLayoutType::Unknown,
        count: 0,
        ecc: false,
        sectored: CacheSectored::No,
    },
    CacheDescriptor { // 0xF9 (Unknown)
        level: CacheLevel::Unknown,
        type_of_cache: CacheType::Unknown,
        size: CacheSize::Unknown,
        associativity: CacheAssociativity::Unknown,
        layout: CacheLayoutType::Unknown,
        count: 0,
        ecc: false,
        sectored: CacheSectored::No,
    },
    CacheDescriptor { // 0xFA (Unknown)
        level: CacheLevel::Unknown,
        type_of_cache: CacheType::Unknown,
        size: CacheSize::Unknown,
        associativity: CacheAssociativity::Unknown,
        layout: CacheLayoutType::Unknown,
        count: 0,
        ecc: false,
        sectored: CacheSectored::No,
    },
    CacheDescriptor { // 0xFB (Unknown)
        level: CacheLevel::Unknown,
        type_of_cache: CacheType::Unknown,
        size: CacheSize::Unknown,
        associativity: CacheAssociativity::Unknown,
        layout: CacheLayoutType::Unknown,
        count: 0,
        ecc: false,
        sectored: CacheSectored::No,
    },
    CacheDescriptor { // 0xFC (Unknown)
        level: CacheLevel::Unknown,
        type_of_cache: CacheType::Unknown,
        size: CacheSize::Unknown,
        associativity: CacheAssociativity::Unknown,
        layout: CacheLayoutType::Unknown,
        count: 0,
        ecc: false,
        sectored: CacheSectored::No,
    },
    CacheDescriptor { // 0xFD (Unknown)
        level: CacheLevel::Unknown,
        type_of_cache: CacheType::Unknown,
        size: CacheSize::Unknown,
        associativity: CacheAssociativity::Unknown,
        layout: CacheLayoutType::Unknown,
        count: 0,
        ecc: false,
        sectored: CacheSectored::No,
    },
    CacheDescriptor { // 0xFE (Unknown)
        level: CacheLevel::Unknown,
        type_of_cache: CacheType::Unknown,
        size: CacheSize::Unknown,
        associativity: CacheAssociativity::Unknown,
        layout: CacheLayoutType::Unknown,
        count: 0,
        ecc: false,
        sectored: CacheSectored::No,
    },
    CacheDescriptor { // 0xFF (Unknown)
        level: CacheLevel::Unknown,
        type_of_cache: CacheType::Unknown,
        size: CacheSize::Unknown,
        associativity: CacheAssociativity::Unknown,
        layout: CacheLayoutType::Unknown,
        count: 0,
        ecc: false,
        sectored: CacheSectored::No,
    },
];